version: "2"

services:

  discoveryservice:
    image: "com.kramkroc/discovery-service"
    restart: always
    hostname: discoveryservice
    container_name: discoveryservice
    ports:
     - "8761:8761"

  configserver:
    image: "com.kramkroc/config-server"
    restart: always  
    depends_on:
      - discoveryservice
    environment:
      EUREKA_URL: "http://discoveryservice:8761/eureka/"

    ports:
      - "8888:8888"

  apigateway:
    image: "com.kramkroc/apigateway:latest"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    environment:
       EUREKA_URL: "http://discoveryservice:8761/eureka/"
    ports:
      - "8087:8087"

  sampleservice:
    image: "com.kramkroc/sample-service"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    environment:
       EUREKA_URL: "http://discoveryservice:8761/eureka/"

networks:
  default:
    external:
      name: refreshscope